service: iot-project

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:
  IoTHandler:
    handler: handler.iot_handler
    events:
      - iot:
          sql: "SELECT *, clientid() AS client_id FROM 'iot'"
          name: iot_project
          description: "iot-project"
          enabled: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    usePoetry: false
